[package]
name = "enum2egui"
version = "0.1.8"
authors = ["Matthew Berger <matthewjordanberger@gmail.com>"]
description = """
enum2egui is a rust derive macro that creates a set of egui ui databindings from arbitrary data structures. 
Supports egui v0.24.1
"""
homepage = "https://github.com/matthewjberger/enum2egui"
repository = "https://github.com/matthewjberger/enum2egui"
keywords = ["egui"]
license = "MIT"
edition = "2021"

[dependencies]
egui = "0.24.1"
enum2egui-derive = { path = "enum2egui-derive", version = "0.1.0" }
hashbrown = { version = "0.14.1", optional = true }

[workspace]
members = ["demo"]

[features]
default = []
hashbrown_derive = ["hashbrown"]
