[package]
name = "enum2egui-demo"
version = "0.1.0"
authors = ["Matthew Berger <matthewjordanberger@gmail.com>"]
edition = "2021"

[dependencies]
egui = "0.26"
enum2str = "0.1.8"
enum2egui = { path = "..", features = ["hashbrown_derive"] }
enum2egui-derive = { path = "../enum2egui-derive" }
eframe = { version = "0.26", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "glow",
] }
hashbrown = { version = "0.14.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"
